### ISSUE TITLE
No job clothes

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/esx_mechanicjob#17]
Job clothes missing in SQL

https://github.com/ESX-Org/esx_mecanojob/blob/8e0320be7a1512718bbbe736a26f5452caef6719/localization/esx_mecanojob_en.sql#L16

**Comment by TankHord** [comment]
what can we do

**Comment by hacklover** [comment]
Do you mean that changing clothes for mecanojob isn't working?
Me I've a problem, can't set clothes for this job (in policejob it works)

**Comment by ralfaparins** [comment]
People... just add the clothes in the SQL.

**Comment by EGUltraTM** [comment]
Here some example clothes we made:
`INSERT INTO `job_grades` VALUES ('22', 'mecano', '0', 'recrue', 'Lehrling', '12', '{\"tshirt_1\":15,\"tshirt_2\":0,\"torso_1\":13,\"torso_2\":0,\"shoes_1\":59,\"shoes_2\":20,\"pants_1\":90, \"pants_2\":1, \"arms\":11, \"helmet_1\":6, \"helmet_2\":2,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}', '{\"tshirt_1\":15,\"tshirt_2\":0,\"torso_1\":23,\"torso_2\":0,\"shoes_1\":62,\"shoes_2\":20,\"pants_1\":93, \"pants_2\":1, \"arms\":0, \"helmet_1\":60, \"helmet_2\":6,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}');
INSERT INTO `job_grades` VALUES ('23', 'mecano', '1', 'novice', 'Geselle', '24', '{\"tshirt_1\":90,\"tshirt_2\":0,\"torso_1\":248,\"torso_2\":8,\"shoes_1\":59,\"shoes_2\":20,\"pants_1\":98, \"pants_2\":3, \"arms\":17, \"helmet_1\":6, \"helmet_2\":2,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}', '{\"tshirt_1\":41,\"tshirt_2\":0,\"torso_1\":252,\"torso_2\":2,\"shoes_1\":62,\"shoes_2\":20,\"pants_1\":103, \"pants_2\":3, \"arms\":0, \"helmet_1\":60, \"helmet_2\":6,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}');
INSERT INTO `job_grades` VALUES ('24', 'mecano', '2', 'experimente', 'Experte', '36', '{\"tshirt_1\":90,\"tshirt_2\":0,\"torso_1\":248,\"torso_2\":8,\"shoes_1\":59,\"shoes_2\":20,\"pants_1\":98, \"pants_2\":3, \"arms\":17, \"helmet_1\":6, \"helmet_2\":2,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}', '{\"tshirt_1\":41,\"tshirt_2\":0,\"torso_1\":252,\"torso_2\":2,\"shoes_1\":62,\"shoes_2\":20,\"pants_1\":103, \"pants_2\":3, \"arms\":0, \"helmet_1\":60, \"helmet_2\":6,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}');
INSERT INTO `job_grades` VALUES ('25', 'mecano', '3', 'chief', 'Vorarbeiter', '48', '{\"tshirt_1\":90,\"tshirt_2\":0,\"torso_1\":248,\"torso_2\":8,\"shoes_1\":59,\"shoes_2\":20,\"pants_1\":98, \"pants_2\":3, \"arms\":17, \"helmet_1\":6, \"helmet_2\":2,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}', '{\"tshirt_1\":41,\"tshirt_2\":0,\"torso_1\":252,\"torso_2\":2,\"shoes_1\":62,\"shoes_2\":20,\"pants_1\":103, \"pants_2\":3, \"arms\":0, \"helmet_1\":60, \"helmet_2\":6,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}');
INSERT INTO `job_grades` VALUES ('26', 'mecano', '4', 'boss', 'Chef', '1', '{\"tshirt_1\":90,\"tshirt_2\":0,\"torso_1\":248,\"torso_2\":8,\"shoes_1\":59,\"shoes_2\":20,\"pants_1\":98, \"pants_2\":3, \"arms\":17, \"helmet_1\":6, \"helmet_2\":1,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}', '{\"tshirt_1\":41,\"tshirt_2\":0,\"torso_1\":252,\"torso_2\":2,\"shoes_1\":62,\"shoes_2\":20,\"pants_1\":103, \"pants_2\":3, \"arms\":0, \"helmet_1\":60, \"helmet_2\":9,\"bags_1\":0,\"bags_2\":0,\"ears_1\":0,\"glasses_1\":0,\"ears_2\":0,\"glasses_2\":0}');
`

**Comment by DanyCryEn** [comment]
i've added clothes in to DB but don't work in game... only ESX_Mechanicjob ,, other Jobs working fine.
