### ISSUE TITLE
Hi, skin mecano job

### ISSUE THREAD

**Issue by Lyccossa** [ESX-Org/esx_mechanicjob#46]
hello I have a problem at the time of putting the skin on mechanical job does not appear check everything but nothing could help me, sorry for my English.
![error](https://user-images.githubusercontent.com/33160324/55769373-97120400-5a4e-11e9-8e8e-a3947d68b91f.png)

but in the other works if they appear

**Comment by FrabaY** [comment]
try to add in the databasev

**Comment by Lyccossa** [comment]
![ambulance job](https://user-images.githubusercontent.com/33160324/56097014-1b381180-5ebd-11e9-9224-001e78fc335a.png)

Hey bro I have another problem, it's about esx ambulance job you want to see? I need help.

Thank you very much for the help of esx mecano.
