### ISSUE TITLE
Owner vehicles Error

### ISSUE THREAD

**Issue by Taker54** [ESX-Org/esx_mechanicjob#58]
Im activated the option

Config.EnableSocietyOwnedVehicles = true

When taking a mechanic vehicle gives this error
SCRIPT ERROR: @esx_society/server/main.lua:334: attempt to index a nil value (local 'store') > ref (@esx_society/server/main.lua:334) > handler (@esx_datastore/server/main.lua:80) > ref (@esx_society/server/main.lua:333) > TriggerServerCallback (@es_extended/server/functions.lua:33) > handler (@es_extended/server/common.lua:88)

**Comment by ElPumpo** [comment]
Install proper sql
