### ISSUE TITLE
Cars don't come straight to the flatbed

### ISSUE THREAD

**Issue by larscrazynl** [ESX-Org/esx_mechanicjob#74]
Hello, 
I've got a custom flatbed and my cars aren't getting on my flatbed properly. 
Is there a solution to this?
PHOTO: https://imgur.com/a/WmomXc4

**Comment by HumanTree92** [comment]
Line 424 you have to manually edit AttachEntityToEntity

**Comment by larscrazynl** [comment]
Thnx it was only de flatbed, i have fixed it now!
Thank you so much!
